---
- name: adding admin user ansible
  become: true
  ansible.builtin.user:
    name: 'ansible'
    shell: '/bin/bash'
    groups: 'admins'
    append: true

- name: Create .ssh directory for user ansible
  become: true
  ansible.builtin.file:
    path: '/home/ansible/.ssh'
    state: directory
    owner: ansible
    group: admins
    mode: 'u=rwx,g=,o='
  changed_when: false
