---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Add admin group
  become: true
  group:
    name: 'admins'
    state: present

- name: Add individual group
  become: true
  group:
    name: '{{ item }}'
    state: present
  with_items: '{{ accounts }}'

- name: Add local users
  become: true
  user:
    name: '{{ item }}'
    shell: '{{ default_shell }}'
    groups: '{{ item }}'
    append: false
  with_items: '{{ accounts }}'
  changed_when: false
  when: not manage_user_passwords | bool

- name: Add local users
  become: true
  user:
    name: '{{ item.key | string }}'
    shell: '{{ default_shell }}'
    groups: '{{ item.key | string }}'
    password: "{{ item.value.0 | string }}"
    append: false
  with_dict: '{{ accounts_with_password }}'
  changed_when: false
  when: manage_user_passwords | bool

- name: Copy .bashrc for local users
  become: true
  copy:
    src: 'files/home_environment/bashrc'
    dest: '/home/{{ item }}/.bashrc'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: 'u=rw,g=r,o='
  with_items: '{{ accounts }}'
  when: home_sweet_home | bool

- name: Copy .vimrc for local users
  become: true
  copy:
    src: 'files/home_environment/vimrc'
    dest: '/home/{{ item }}/.vimrc'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: 'u=rw,g=r,o='
  with_items: '{{ accounts }}'
  when: home_sweet_home | bool

- name: Add ansible user
  become: true
  user:
    name: 'ansible'
    shell: '/bin/bash'
    groups: 'admins'
    append: true

- name: Create .ssh directory for user ansible
  become: true
  file:
    path: '/home/ansible/.ssh'
    state: directory
    owner: ansible
    group: admins
    mode: 'u=rwx,g=,o='
  changed_when: false

- name: Create /etc/sudoers.d directory
  become: true
  file:
    path: '/etc/sudoers.d'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=x,o=x'

- name: Copy sudoers file
  become: true
  copy:
    src: 'files/home_environment/sudoers'
    dest: '/etc/sudoers.d/ansible'
    owner: root
    group: root
    mode: 'u=r,g=r,o='
    validate: /usr/sbin/visudo -cf %s

- name: "adding existing user '{{ item }}' to group admins"
  become: true
  user:
    name: '{{ item }}'
    groups: admins
    append: true
  with_items: '{{ admins }}'
  changed_when: false
