---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: create configured and admin groups and users
  ansible.builtin.include_tasks: accounts.yml

- name: create vim and bash dotfile
  ansible.builtin.include_tasks: dotflies.yml
  when: home_sweet_home | bool

- name: create access for user ansible
  ansible.builtin.include_tasks: ansible-user.yml

- name: manage sudo access for admin group
  ansible.builtin.include_tasks: sudoers.yml

- name: adding configured user to admin group
  ansible.builtin.include_tasks: admin-group.yml
